---
 


- name: Clone Deepmatrix Metashape
  ansible.builtin.git:
    repo: https://github.com/DeepMatrixIO/metashape-job.git
    dest: "{{metashape_directory}}"
    separate_git_dir: /src/metashape-job.git
    register : git_clone
- debug : 
     var : git_clone.stdout_line
- debug : 
     var : git_clone.stderr_line

- name : Execute Metashape
  command: mvn exec:java -Dexec.mainClass="io.deepmatrix.compute.JobScheduler"
  become : true
  register : metashape_exec
- debug : 
     var : metashape_exec.stdout_line
- debug : 
     var : metashape_exec.stderr_line

- name : Install Packages
  apt:
   name: "{{item}}"
   state: present
   with_items: 
    - "{{package_names}}"


- name: Metashape Download
  get_url: 
     url: https://s3-eu-west-1.amazonaws.com/download.agisoft.com/metashape{{metashape_version}}amd64.tar.gz
     dest: "{{home_dir}}"
  become: true   

- name : Install Metashape
  unarchive:
   src: {{Metashape_tar}}
   dest : {{Metashape_path}}
   copy: no 
  become: true
  