---


package_names:
 - maven
 - python3.9
 - openjdk-11-jdk
 - openjdk-17-jdk
#  - libxcb-xinerama10


arguments: #add arguments

product_id : # add product_id


metashape_directory: # add directory_path


metashape_version: _1_8_3_

