---

- name : Quarkus Installation
  ansible.builtin.command: "{{item}}"
  with_items:
     - curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
     - curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio


- name : Create deepmatrix app
  ansible.builtin.command: quarkus create app io.deepmatrix.service:data-service \
    --extension=resteasy-reactive,resteasy-reactive-jackson,quarkus-smallrye-openapi,quarkus-hibernate-orm-panache,quarkus-jdbc-postgresq,hibernate-validator