---

- name : Install packages   
  apt : 
    name : {{item}}
    with_items: 
    - "{{package_names}}"


- name: Clone tusd repo
  ansible.builtin.git:
    repo: git clone https://github.com/tus/tusd.git
    dest: {{git_directory}}
    single_branch: yes
    version: master
    register : git_clone
- debug : 
     var : git_clone.stdout_line
- debug : 
     var : git_clone.stderr_line


- name : tusd build 
  ansible.builtin.command : cd {{git_directory}}/tusd && {{tusd_build}}
  register : tusd_build_var
- debug : 
   var : tusd_build_var.stdout_line
- debug :
   var: tusd_build_var.stderr_line


- name : running tusd server
  ansible.builtin.command: ./tusd -upload-dir=./data --hooks-http http://localhost:8080/tusd/postcreate --hooks-enabled-events post-finish





